#!/bin/bash
# run sequential compress of parallel compress with given number of mpi tasks

function print_usage {
    echo "Usage: compress [seq|mpi|omp] [n]"
    echo ""
    echo "seq: run sequential implementation"
    echo "mpi: run parallel implementation with the given number of mpi tasks"
    echo "omp: run omp implementation"
    echo "n:   number of mpi tasks to use, omit for max possible tasks"
}

function check_executable {
    if [[ ! -f "$1" ]]
    then
        echo "executable $1 not found, running make"
        make
    fi
}

if [[ "$1" = "seq" ]]
then
    check_executable "seq-mpi-bin"
    ./seq-mpi-bin
elif [[ "$1" = "mpi" ]]
then
    check_executable "seq-mpi-bin"
    mpirun -np "$2" ./seq-mpi-bin -p
elif [[ "$1" = "omp" ]]
then
    check_executable "omp-bin"
    ./omp-bin -o
else
    print_usage
fi
